### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by lorebored** [mooncoffee1/Envycontrol-Gtk#1]
Please release a faltpak Version so we can run your app in the most of the distros

**Comment by mooncoffee1** [comment]
well, u can run it on any distro, its not soo complicated, just install gtk3 envycontrol and cargo for your distro version bc they may have different name, then run my installer which will do everything.

**Comment by mooncoffee1** [comment]
https://github.com/bayasdev/envycontrol?tab=readme-ov-file#ubuntu--debian - here is the instruction for ubuntu/debian for envycontrol



> Please release a faltpak Version so we can run your app in the most of the distros

sudo apt-get install libgtk-3-dev  -- for gtk 


curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh   -- and this is for cargo and rust

then just do the tutorial from my git repo
